/* Generated by re2c 0.16 on Fri Apr 28 09:26:15 2017 */
#line 1 "calc.l"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "calc.tab.h"
extern char *YYCURSOR;

int yylex()
{
    if (*YYCURSOR == '\0') return 0;

    char num[100];
    char *start = YYCURSOR;

    
#line 18 "calc.lex.c"
{
	int yych;
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy4;
	case '*':	goto yy6;
	case '+':	goto yy8;
	case '-':	goto yy10;
	case '/':	goto yy12;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy14;
	default:	goto yy2;
	}
yy2:
	++YYCURSOR;
#line 18 "calc.l"
	{ fprintf(stderr, "lex error: %s\n", start); }
#line 44 "calc.lex.c"
yy4:
	++YYCURSOR;
#line 24 "calc.l"
	{ yylval = '\n'; return LF; }
#line 49 "calc.lex.c"
yy6:
	++YYCURSOR;
#line 22 "calc.l"
	{ yylval = '*'; return MUL; }
#line 54 "calc.lex.c"
yy8:
	++YYCURSOR;
#line 20 "calc.l"
	{ yylval = '+'; return PLUS; }
#line 59 "calc.lex.c"
yy10:
	++YYCURSOR;
#line 21 "calc.l"
	{ yylval = '-'; return MINUS; }
#line 64 "calc.lex.c"
yy12:
	++YYCURSOR;
#line 23 "calc.l"
	{ yylval = '/'; return DIV; }
#line 69 "calc.lex.c"
yy14:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy14;
	default:	goto yy16;
	}
yy16:
#line 19 "calc.l"
	{ strncpy(num, start, YYCURSOR - start); num[YYCURSOR - start] = '\0'; yylval = atoi(num); return NUM; }
#line 89 "calc.lex.c"
}
#line 25 "calc.l"

}
