/* Generated by re2c 0.16 on Fri Apr 28 07:30:59 2017 */
#line 1 "calc.l"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "calc.tab.h"
extern char *YYCURSOR;

int yylex()
{
    if (*YYCURSOR == '\0') return 0;

    char num[100];
    char *start = YYCURSOR;

    
#line 18 "calc.lex.c"
{
	int yych;
	yych = *YYCURSOR;
	switch (yych) {
	case '*':	goto yy3;
	case '+':	goto yy5;
	case '-':	goto yy7;
	case '/':	goto yy9;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy11;
	default:	goto yy2;
	}
yy2:
yy3:
	++YYCURSOR;
#line 21 "calc.l"
	{ yylval = '*'; return MUL; }
#line 44 "calc.lex.c"
yy5:
	++YYCURSOR;
#line 19 "calc.l"
	{ yylval = '+'; return PLUS; }
#line 49 "calc.lex.c"
yy7:
	++YYCURSOR;
#line 20 "calc.l"
	{ yylval = '-'; return MINUS; }
#line 54 "calc.lex.c"
yy9:
	++YYCURSOR;
#line 22 "calc.l"
	{ yylval = '/'; return DIV; }
#line 59 "calc.lex.c"
yy11:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy11;
	default:	goto yy13;
	}
yy13:
#line 18 "calc.l"
	{ strncpy(num, start, YYCURSOR - start); num[YYCURSOR - start] = '\0'; yylval = atoi(num); return NUM; }
#line 79 "calc.lex.c"
}
#line 23 "calc.l"

}
